# Hungarian Method

In [3]:
import sys
import numpy as np
sys.path.append("..")
from ido import hungarian

In [4]:
mtest = np.array([[3,  8, 2, 10,  3],
                  [8,  7, 2,  9,  7],
                  [6,  4, 2,  7,  5],
                  [8,  4, 2,  3,  5],
                  [9, 10, 6,  9, 10]])
hungarian(mtest)

[[1 6 0 8 1]
 [6 5 0 7 5]
 [4 2 0 5 3]
 [6 2 0 1 3]
 [3 4 0 3 4]] 

[[0 4 0 7 0]
 [5 3 0 6 4]
 [3 0 0 4 2]
 [5 0 0 0 2]
 [2 2 0 2 3]]


In [7]:
mtest2 = np.array([[3, 9, 2,  3, 7],
                   [6, 1, 5,  6, 6],
                   [9, 4, 7, 10, 3],
                   [2, 5, 4,  2, 1],
                   [9, 6, 2,  4, 5]])

hungarian(mtest2)

[[1 7 0 1 5]
 [5 0 4 5 5]
 [6 1 4 7 0]
 [1 4 3 1 0]
 [7 4 0 2 3]] 

[[0 7 0 0 5]
 [4 0 4 4 5]
 [5 1 4 6 0]
 [0 4 3 0 0]
 [6 4 0 1 3]]
