In [1]:
import numpy as np
from scipy.misc import comb
from itertools import combinations
from scipy.linalg import det

In [2]:
A = np.array([
    [1, -1, 1],
    [2, -1, 2],
    [3, -2, 3],
    [1,  0, 0],
    [0,  1, 0],
    [0,  0, 1]
])

b = np.array([10, 40, 50, 0, 0, 0])

In [3]:
A[0:3,:]

array([[ 1, -1,  1],
       [ 2, -1,  2],
       [ 3, -2,  3]])

In [4]:
b[[0,1,2]]

array([10, 40, 50])

In [5]:
from scipy.linalg import solve

In [6]:
solve(A[(0,1,3), :], b[list((0, 1, 3))])

array([  0.,  20.,  30.])

In [7]:
A_comb = [comb for comb in combinations(range(6), 3)]

# 3)
Sean 
$$
\begin{bmatrix}
1 & -1 &1 \\ 
 2&-1  &2 \\ 
 3&  -2&3 
\end{bmatrix}
$$

In [27]:
for comb in A_comb:
    A_perm = A[comb, :]
    b_perm = b[list(comb)]
    detA = det(A_perm)
    print(comb)
    print(A_perm, b_perm)
    print("Det: {}\n".format(detA))
    
    if detA != 0:
        fpoints = solve(A_perm, b_perm)
        ans = np.dot(A[0:3,:], fpoints)
        print("[x0, x1, x2] = ", fpoints)
        
        
        if np.all(ans == np.array([10, 40, 50])):
            print("***Extreme Point***")
        
    print("--------------\n")

(0, 1, 2)
[[ 1 -1  1]
 [ 2 -1  2]
 [ 3 -2  3]] [10 40 50]
Det: 0.0

--------------

(0, 1, 3)
[[ 1 -1  1]
 [ 2 -1  2]
 [ 1  0  0]] [10 40  0]
Det: -1.0

[x0, x1, x2] =  [  0.  20.  30.]
***Extreme Point***
--------------

(0, 1, 4)
[[ 1 -1  1]
 [ 2 -1  2]
 [ 0  1  0]] [10 40  0]
Det: 0.0

--------------

(0, 1, 5)
[[ 1 -1  1]
 [ 2 -1  2]
 [ 0  0  1]] [10 40  0]
Det: 1.0

[x0, x1, x2] =  [ 30.  20.   0.]
***Extreme Point***
--------------

(0, 2, 3)
[[ 1 -1  1]
 [ 3 -2  3]
 [ 1  0  0]] [10 50  0]
Det: -1.0

[x0, x1, x2] =  [  2.36847579e-15   2.00000000e+01   3.00000000e+01]
***Extreme Point***
--------------

(0, 2, 4)
[[ 1 -1  1]
 [ 3 -2  3]
 [ 0  1  0]] [10 50  0]
Det: 0.0

--------------

(0, 2, 5)
[[ 1 -1  1]
 [ 3 -2  3]
 [ 0  0  1]] [10 50  0]
Det: 1.0

[x0, x1, x2] =  [ 30.  20.   0.]
--------------

(0, 3, 4)
[[ 1 -1  1]
 [ 1  0  0]
 [ 0  1  0]] [10  0  0]
Det: 1.0

[x0, x1, x2] =  [  0.   0.  10.]
--------------

(0, 3, 5)
[[ 1 -1  1]
 [ 1  0  0]
 [ 0  0  1]] [10  0  0]
Det: 1.