In [6]:
import numpy as np
from scipy.misc import comb
from itertools import combinations
from scipy.linalg import det, solve

In [2]:
A = np.array([
    [1, -1, 1],
    [2, -1, 2],
    [3, -2, 3],
    [1,  0, 0],
    [0,  1, 0],
    [0,  0, 1]
])

b = np.array([10, 40, 50, 0, 0, 0])

In [3]:
A[0:3,:]

array([[ 1, -1,  1],
       [ 2, -1,  2],
       [ 3, -2,  3]])

In [4]:
b[[0,1,2]]

array([10, 40, 50])

In [5]:
from scipy.linalg import solve

In [6]:
solve(A[(0,1,3), :], b[list((0, 1, 3))])

array([  0.,  20.,  30.])

In [4]:
A_comb = [comb for comb in combinations(range(6), 3)]

# 3)
Sean 
$$
\begin{bmatrix}
1 & -1 &1 \\ 
 2&-1  &2 \\ 
 3&  -2&3 
\end{bmatrix}
$$

In [8]:
A_comb = [comb for comb in combinations(range(6), 3)]
for comb in A_comb:
    A_perm = A[comb, :]
    b_perm = b[list(comb)]
    detA = det(A_perm)
    print(comb)
    print(A_perm, b_perm)
    print("Det: {}\n".format(detA))
    
    if detA != 0:
        fpoints = solve(A_perm, b_perm)
        ans = np.dot(A[0:3,:], fpoints)
        print("[x0, x1, x2] = ", fpoints)
        
        
        if np.all(ans == np.array([10, 40, 50])):
            print("***Extreme Point***")
        
    print("--------------\n")

(0, 1, 2)
[[ 1  1  1]
 [ 1 -1  1]
 [ 2 -1  2]] [ 1 10 40]
Det: 0.0

--------------

(0, 1, 3)
[[ 1  1  1]
 [ 1 -1  1]
 [ 3 -2  3]] [ 1 10 50]
Det: 0.0

--------------

(0, 1, 4)
[[ 1  1  1]
 [ 1 -1  1]
 [ 1  0  0]] [ 1 10  0]
Det: 2.0

[x0, x1, x2] =  [ 0.  -4.5  5.5]
--------------

(0, 1, 5)
[[ 1  1  1]
 [ 1 -1  1]
 [ 0  1  0]] [ 1 10  0]
Det: 0.0

--------------

(0, 2, 3)
[[ 1  1  1]
 [ 2 -1  2]
 [ 3 -2  3]] [ 1 40 50]
Det: 0.0

--------------

(0, 2, 4)
[[ 1  1  1]
 [ 2 -1  2]
 [ 1  0  0]] [ 1 40  0]
Det: 3.0

[x0, x1, x2] =  [ -8.88178420e-16  -1.26666667e+01   1.36666667e+01]
--------------

(0, 2, 5)
[[ 1  1  1]
 [ 2 -1  2]
 [ 0  1  0]] [ 1 40  0]
Det: 0.0

--------------

(0, 3, 4)
[[ 1  1  1]
 [ 3 -2  3]
 [ 1  0  0]] [ 1 50  0]
Det: 5.0

[x0, x1, x2] =  [  3.55271368e-15  -9.40000000e+00   1.04000000e+01]
--------------

(0, 3, 5)
[[ 1  1  1]
 [ 3 -2  3]
 [ 0  1  0]] [ 1 50  0]
Det: 0.0

--------------

(0, 4, 5)
[[1 1 1]
 [1 0 0]
 [0 1 0]] [1 0 0]
Det: 1.0

[x0, x1, x2] =  [

In [22]:
# Computing Extreme Solutions
A_comb = [comb for comb in combinations(range(7), 3)]
A = np.array([
    [1, -1, 1],
    [2, -1, 2],
    [3, -2, 3],
    [1,  0, 0],
    [0,  1, 0],
    [0,  0, 1],
    [1,  1, 1]
])

b = np.array([10, 40, 50, 0, 0, 0, 1])
b_rest = np.array([10, 40, 50])

for ix, comb in enumerate(A_comb):
    A_perm = A[comb, :]
    b_perm = b[list(comb)]
    detA = det(A_perm)
    print(ix, comb)
    print(A_perm, b_perm)
    print("Det: {}\n".format(detA))
    
    if detA != 0:
        fpoints = solve(A_perm, b_perm)
        ans = np.dot(A[0:3,:], fpoints)
        print("[x0, x1, x2] = ", fpoints)
        print("∑", sum(fpoints))
        print(ans <= b_rest)
        if(sum(fpoints) == 1 and np.all(ans <= b_rest)):
            print("****EXTREME DIRECTION****")
        
        
        
    print("--------------\n")

0 (0, 1, 2)
[[ 1 -1  1]
 [ 2 -1  2]
 [ 3 -2  3]] [10 40 50]
Det: 0.0

--------------

1 (0, 1, 3)
[[ 1 -1  1]
 [ 2 -1  2]
 [ 1  0  0]] [10 40  0]
Det: -1.0

[x0, x1, x2] =  [  0.  20.  30.]
∑ 50.0
[ True  True  True]
--------------

2 (0, 1, 4)
[[ 1 -1  1]
 [ 2 -1  2]
 [ 0  1  0]] [10 40  0]
Det: 0.0

--------------

3 (0, 1, 5)
[[ 1 -1  1]
 [ 2 -1  2]
 [ 0  0  1]] [10 40  0]
Det: 1.0

[x0, x1, x2] =  [ 30.  20.   0.]
∑ 50.0
[ True  True  True]
--------------

4 (0, 1, 6)
[[ 1 -1  1]
 [ 2 -1  2]
 [ 1  1  1]] [10 40  1]
Det: 0.0

--------------

5 (0, 2, 3)
[[ 1 -1  1]
 [ 3 -2  3]
 [ 1  0  0]] [10 50  0]
Det: -1.0

[x0, x1, x2] =  [  2.36847579e-15   2.00000000e+01   3.00000000e+01]
∑ 50.0
[ True  True  True]
--------------

6 (0, 2, 4)
[[ 1 -1  1]
 [ 3 -2  3]
 [ 0  1  0]] [10 50  0]
Det: 0.0

--------------

7 (0, 2, 5)
[[ 1 -1  1]
 [ 3 -2  3]
 [ 0  0  1]] [10 50  0]
Det: 1.0

[x0, x1, x2] =  [ 30.  20.   0.]
∑ 50.0
[False  True False]
--------------

8 (0, 2, 6)
[[ 1 -1  1]
 [ 3 -2  3