In [1]:
import numpy as np
from sympy import *
init_printing(use_unicode=True)

In [29]:
A = np.array([
    [2, 1, 1, 1, 0, 0],
    [4, 2, 3, 0, 1, 0],
    [2, 5, 5, 0, 0, 1]
], dtype=np.float64)
z = [[-1, -2, 1, 0, 0, 0]]
b = [0, 14, 28, 30]

A = np.r_[z, A]
A = np.c_[A, b]
A

array([[ -1.,  -2.,   1.,   0.,   0.,   0.,   0.],
       [  2.,   1.,   1.,   1.,   0.,   0.,  14.],
       [  4.,   2.,   3.,   0.,   1.,   0.,  28.],
       [  2.,   5.,   5.,   0.,   0.,   1.,  30.]])

**$x_2$ increases the most. $x_6$ is the blockage** 

In [30]:
A[3,:] = A[3,:] / 5.0
A

array([[ -1. ,  -2. ,   1. ,   0. ,   0. ,   0. ,   0. ],
       [  2. ,   1. ,   1. ,   1. ,   0. ,   0. ,  14. ],
       [  4. ,   2. ,   3. ,   0. ,   1. ,   0. ,  28. ],
       [  0.4,   1. ,   1. ,   0. ,   0. ,   0.2,   6. ]])

In [31]:
A[0,:] = A[0,:] + A[3,:] * 2
A[1,:] = A[1,:] + A[3,:] * -1  
A[2,:] = A[2,:] + A[3,:] * -2

A

array([[ -0.2,   0. ,   3. ,   0. ,   0. ,   0.4,  12. ],
       [  1.6,   0. ,   0. ,   1. ,   0. ,  -0.2,   8. ],
       [  3.2,   0. ,   1. ,   0. ,   1. ,  -0.4,  16. ],
       [  0.4,   1. ,   1. ,   0. ,   0. ,   0.2,   6. ]])

**$x_1$ increases the most. $x_4$ is the blockage**

In [35]:
A[1:,-1] / A[1:,0] 

array([  5.,   5.,  15.])

In [38]:
A[1,:] = A[1,:] * 1/A[1,0]
A

array([[ -0.2  ,   0.   ,   3.   ,   0.   ,   0.   ,   0.4  ,  12.   ],
       [  1.   ,   0.   ,   0.   ,   0.625,   0.   ,  -0.125,   5.   ],
       [  3.2  ,   0.   ,   1.   ,   0.   ,   1.   ,  -0.4  ,  16.   ],
       [  0.4  ,   1.   ,   1.   ,   0.   ,   0.   ,   0.2  ,   6.   ]])

In [59]:
A[0,:] = A[0,:] + A[1,:] * - A[0,0]
A[2,:] = A[2,:] + A[1,:] * - A[2,0]
A[3,:] = A[3,:] + A[1,:] * - A[3,0]
A

array([[  0.   ,   0.   ,   3.   ,   0.125,   0.   ,   0.375,  13.   ],
       [  1.   ,   0.   ,   0.   ,   0.625,   0.   ,  -0.125,   5.   ],
       [  0.   ,   0.   ,   1.   ,  -2.   ,   1.   ,   0.   ,   0.   ],
       [  0.   ,   1.   ,   1.   ,  -0.25 ,   0.   ,   0.25 ,   4.   ]])

# Dictionary 

In [24]:
x1, x2, x3, x4, x5, x6 = symbols("x1 x2 x3 x4 x5 x6")

In [4]:
def print_problem(Z, constraints):
    print("Z = ", Z)
    for c in constraints:
        print(c, "= 0")

In [25]:
# Initial
Z = x1 + 2*x2 - x3

c1 = 2*x1 +   x2 +   x3 + x4         - 14
c2 = 4*x1 + 2*x2 + 3*x3 +     x5     - 28
c3 = 2*x1 + 5*x2 + 5*x3 +         x6 - 30

print_problem(Z, [c1, c2, c3])

Z =  x1 + 2*x2 - x3
2*x1 + x2 + x3 + x4 - 14 = 0
4*x1 + 2*x2 + 3*x3 + x5 - 28 = 0
2*x1 + 5*x2 + 5*x3 + x6 - 30 = 0


In [26]:
# Finding where the blockage happens
print(solve(c1.subs({x1:0, x3:0, x4:0}), x2)) # In terms of x4
print(solve(c2.subs({x1:0, x3:0, x5:0}), x2)) # In terms of x5
print(solve(c3.subs({x1:0, x3:0, x6:0}), x2), "x6 goes out") # In terms of x6

[14]
[14]
[6] x6 goes out


In [27]:
#### Update the table ####
# third constraint in terms of x2
c3 = solve(c3, x2)[0]
c1 = c1.subs(x2, c3)
c2 = c2.subs(x2, c3)

Z = Z.subs(x2, c3)

print_problem(Z, [c1, c2, c3])

Z =  x1/5 - 3*x3 - 2*x6/5 + 12
8*x1/5 + x4 - x6/5 - 8 = 0
16*x1/5 + x3 + x5 - 2*x6/5 - 16 = 0
-2*x1/5 - x3 - x6/5 + 6 = 0


In [28]:
# Find new blockage (x1 increases the most)
print(solve(c1.subs({x3:0, x6:0, x4:0}), x1))
print(solve(c2.subs({x3:0, x6:0, x5:0}), x1))
print(solve(c3.subs({x3:0, x6:0, x2:0}), x1))

# Choose x4 to go out. It could've been either x4 or x5

[5]
[5]
[15]


In [31]:
c1 = solve(c1, x1)[0]
c2 = c2.subs(x1, c1)
c3 = c3.subs(x1, c1)

Z = Z.subs(x1, c1)

print_problem(Z, [c1, c2, c3])

Z =  -3*x3 - x4/8 - 3*x6/8 + 13
-5*x4/8 + x6/8 + 5 = 0
x3 - 2*x4 + x5 = 0
-x3 + x4/4 - x6/4 + 4 = 0


Since $\frac{\partial Z}{\partial x_i} \leq 0 \ \forall \ i$, we know we have reached the Max.

# Matrix Form

In [334]:
A = Matrix([
    [ 1, 1, -2, 1, 0],
    [-3, 1,  2, 0, 1]
])

C = Matrix([0, -2, -1, 0, 0])

b = Matrix([7, 3])

var = {"b": [3, 4], # basic
       "nb": [0, 1, 2]} # non-basic

B = A[:,var["b"]]
N = A[:, var["nb"]]

C_b = C[var["b"],:]

In [335]:
A

⎡1   1  -2  1  0⎤
⎢               ⎥
⎣-3  1  2   0  1⎦

In [336]:
B

⎡1  0⎤
⎢    ⎥
⎣0  1⎦

In [337]:
N

⎡1   1  -2⎤
⎢         ⎥
⎣-3  1  2 ⎦

In [338]:
C_b

⎡0⎤
⎢ ⎥
⎣0⎦

In [339]:
## X1 gets in the base. From column 1 in A, 
# we choose which variable goes out
-C[var["nb"], :]

⎡0⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣1⎦

In [340]:
# Make a vector where only the entering
# variable takes a value of 1
Xp = Matrix([0 for x in range(3)])
Xp[1] = 1

In [341]:
Xp

⎡0⎤
⎢ ⎥
⎢1⎥
⎢ ⎥
⎣0⎦

In [342]:
# Values to choose which variable to take out
# (if the problem is bounded)
Yp = B.inv() * N * Xp

In [343]:
Yp

⎡1⎤
⎢ ⎥
⎣1⎦

In [344]:
# The second variable in the base: x4, goes out
for bi, yi in zip(b, Yp):
    print(bi / yi)

7
3


#### Update!

In [346]:
# Update the table (i.e. update the
# dictionary where the basic and non-basic
# variables are chosen)
var = {"b": [3, 1], # basic
       "nb": [0, 4, 2]} # non-basic

B = A[:,var["b"]]
N = A[:, var["nb"]]

C_b = C[var["b"],:]

In [347]:
C_b, B, N

⎛⎡0 ⎤, ⎡1  1⎤, ⎡1   0  -2⎤⎞
⎜⎢  ⎥  ⎢    ⎥  ⎢         ⎥⎟
⎝⎣-2⎦  ⎣0  1⎦  ⎣-3  1  2 ⎦⎠

$$
    B^{-1}A
$$

In [348]:
B.inv() * A

⎡4   0  -4  1  -1⎤
⎢                ⎥
⎣-3  1  2   0  1 ⎦

$$
B^{-1}b
$$

In [349]:
Bb = B.inv() * b
Bb

⎡4⎤
⎢ ⎥
⎣3⎦

$$
    \bar Z = \bar C B^{-1} \bar b
$$

In [380]:
(C_b.T * B.inv() * b)[0]

ShapeError: Matrices size mismatch.

$$
    \bar x = \bar C B^{-1} A - C
$$

In [351]:
# X0 decreases the most; X0 is not B.V.
C = C_b.T * B.inv() * A - C.T
C

[6  0  -3  0  -2]

In [352]:
Xp = Matrix([0 for x in range(3)])
Xp[0] = 1
Xp

⎡1⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣0⎦

In [353]:
Yp = B.inv() * N * Xp
Yp

⎡4 ⎤
⎢  ⎥
⎣-3⎦

In [354]:
# X3 goes out
for bi, yi in zip(Bb, Yp):
    print(bi / yi)

1
-1


#### Update!

In [356]:
# Update the table (i.e. update the
# dictionary where the basic and non-basic
# variables are chosen)
var = {"b": [0, 1], # basic
       "nb": [3, 4, 2]} # non-basic

B = A[:,var["b"]]
N = A[:, var["nb"]]

C_b = C[:,var["b"]]

In [358]:
A

⎡1   1  -2  1  0⎤
⎢               ⎥
⎣-3  1  2   0  1⎦

In [357]:
C_b, B, N

⎛[6  0], ⎡1   1⎤, ⎡1  0  -2⎤⎞
⎜        ⎢     ⎥  ⎢        ⎥⎟
⎝        ⎣-3  1⎦  ⎣0  1  2 ⎦⎠

$$
    B^{-1}A
$$

In [359]:
B.inv() * A

⎡1  0  -1  1/4  -1/4⎤
⎢                   ⎥
⎣0  1  -1  3/4  1/4 ⎦

$$
B^{-1}b
$$

In [402]:
Bb = B.inv() * b
Bb

⎡1⎤
⎢ ⎥
⎣6⎦

$$
    \bar Z = \bar C_B B^{-1} \bar b
$$

In [403]:
(C_b * B.inv() * Bb)[0]

In [405]:
Matrix([-6, -3]).T * Bb

[-24]

In [392]:
b

⎡7⎤
⎢ ⎥
⎣3⎦

$$
    \bar x = \bar C B^{-1} A - C
$$

In [319]:
# X2 decreases the most; X2 is not B.V.
C_b * B.inv() * A - C

[0  0  -3  3/2  1/2]