In [59]:
import numpy as np
from numpy.linalg import inv

In [139]:
A = np.array([
    [3, 7, 3, 1, 0],
    [2, 2, 6, 0, 1]
])

b = np.array([[10, 4]]).T

C = np.array([[60, 84, 72, 0, 0]])

bvars = [1, 2]
# X2 and X5 are the non-basic variables
B = A[:, bvars]
Cb = C[:,bvars]

$$
    B^{-1}\bar b
$$

In [140]:
inv(B) @ b

array([[ 1.33333333],
       [ 0.22222222]])

$$
    B^{-1}A
 $$

In [141]:
inv(B) @ A

array([[ 0.33333333,  1.        ,  0.        ,  0.16666667, -0.08333333],
       [ 0.22222222,  0.        ,  1.        , -0.05555556,  0.19444444]])

In [142]:
-7/4

-1.75

$$
    \bar C_b B^{-1}\bar A - C
$$

In [143]:
Cb @ (inv(B) @ A) - C

array([[ -1.60000000e+01,   0.00000000e+00,  -1.42108547e-14,
          1.00000000e+01,   7.00000000e+00]])

$$
    \bar C_b B ^{-1} \bar b
$$

In [144]:
Cb @ (inv(B) @ b)

array([[ 128.]])