In [65]:
import numpy as np
from numpy.linalg import inv

In [68]:
A = np.array([
    [3, 7, 3, 1, 0],
    [2, 2, 6, 0, 1]
])

b = np.array([[10, 4]]).T

C = np.array([[60, 84, 72, 0, 0]])

bvars = [1, 4]
# X2 and X5 are the non-basic variables
B = A[:, bvars]
Cb = C[:,bvars]

$$
    B^{-1}\bar b
$$

In [69]:
inv(B) @ b

array([[ 1.42857143],
       [ 1.14285714]])

$$
    B^{-1}A
 $$

In [70]:
inv(B) @ A

array([[ 0.42857143,  1.        ,  0.42857143,  0.14285714,  0.        ],
       [ 1.14285714,  0.        ,  5.14285714, -0.28571429,  1.        ]])

$$
    \bar C_b B^{-1}\bar A - C
$$

In [71]:
Cb @ (inv(B) @ A) - C

array([[-24.,   0., -36.,  12.,   0.]])

$$
    \bar C_b B ^{-1} \bar b
$$

In [72]:
Cb @ (inv(B) @ b)

array([[ 120.]])